### ISSUE TITLE
Excuse me it doesnt work. 

### ISSUE THREAD

**Issue by TeraPlayer** [fatinahrm/Fake-Attack-Speed#1]
[23:49:24.349] [mods] ERROR: Module "PSP" (skill-prediction) could not be loaded!
[23:49:24.350] [mods] ERROR: Please contact the module's author: https://github.com/tera-mods/skill-prediction/issues
[23:49:24.354] Error: [dispatch] [skill-prediction] hook: Error: version 8 of message (name: "S_ACTION_STAGE", code: 58670) is outdated and cannot be used anymore
    at Dispatch.createHook (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new SkillPrediction (E:\TeraToolbox\mods\skill-prediction-master\lib\index.js:1:23042)
    at ModuleManager.load (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (E:\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (E:\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by fatinahrm** [comment]
Yes, because it is outdated... since i took a rest from playing TERA...
